# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92a32954fc42c1dfeb49496bcd55e9883655cda5b61696c4058c7f6156d6c171e0531496da72b96509694b2318c98fed9f1925d202aed19c778c1c3377b56c6f

test:
  secret_key_base: 204ba16b37d0f9c2e073169533ffa7dc0b15b0a6279cb5f864fb397ad66299aff837097b1f330041614c8b6a904411d5544cef327f6fd3853a9263300feb7bb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
